styles/styles.css

Test URLs:
- After: https://32-styles-add-styles-for-sections--netcentric--hlxsites.hlx.page/

Add CN colors to styles.css

---

blocks/cards/cards.css
styles/styles.css

Fix #38
Depends on #39
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/who-we-are
- After: https://38-card-icon-text--netcentric--hlxsites.hlx.page/who-we-are

feat: cards icon with text

---

scripts/scripts.js

https://icons-loading--netcentric--hlxsites.hlx.live/who-we-are
vs. 
https://main--netcentric--hlxsites.hlx.live/who-we-are

chore: move icons in loading sequence

---

styles/styles.css

Fix #32 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/our-industries
- After: https://section-styles--netcentric--hlxsites.hlx.page/our-industries

chore: add section backgrounds

---

package.json

Add lint-fix command
Test URLs:
- After: https://add_lint_fix--netcentric--hlxsites.hlx.page/

Add lint-fix command

---

blocks/form/form.css
blocks/form/form.js
icons/checkbox-checked.svg
icons/checkbox.svg

Fix #8
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/lets-talk
- After: https://issue-8--netcentric--hlxsites.hlx.page/lets-talk

feat: form

---

blocks/cards/cards.css

Fix #50 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/who-we-are, https://main--netcentric--hlxsites.hlx.page/careers/social-responsibility-netcentric 
- After: https://issue-50--netcentric--hlxsites.hlx.page/who-we-are, https://issue-50--netcentric--hlxsites.hlx.page/careers/social-responsibility-netcentric

feat: teaser version of cards block

---

helix-query.yaml

Fix query index definition
Test URLs:
- After: https://index-fix--netcentric--hlxsites.hlx.page/

fix: fix query index definition

---

helix-query.yaml

Fix borken index
Test URLs:
- After: https://<branch>--netcentric--hlxsites.hlx.page/

fix: index fix

---

blocks/related-articles/related-articles.css
blocks/social/social.css
blocks/social/social.js
styles/styles.css

Fix #61
Test URLs:
- After: https://61-cards-social--netcentric--hlxsites.hlx.page/

feat: social cards

---

blocks/hero/hero.css

Test URLs:
- After: https://hotfix-missing-selectors--netcentric--hlxsites.hlx.page/

hotfix: add missing selectors

---

styles/styles.css

add missing section default colors
Fix #32 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/drafts/mhaack/sections
- After: https://section-colors--netcentric--hlxsites.hlx.page/drafts/mhaack/sections

chore: add missing section default colors

---

blocks/hero/hero.css
blocks/related-blogs/related-blogs.css
blocks/related-blogs/related-blogs.js
styles/styles.css

Fixes related header styles & dynamic heading
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/insights/2022/09/take-your-cx-strategy
- After: https://related-header--netcentric--hlxsites.hlx.page/insights/2022/09/take-your-cx-strategy

chore: fix styles clean up related blogs

---

scripts/delayed.js

Add Adobe Launch and initialise dataLayer in a delayed/async way. Distinguish between stage and prod property.
Fix #28 
Test URLs:
- Original: https://www.netcentric.biz/
- Before: https://main--netcentric--hlxsites.hlx.live
- After: https://issue-28-analytics--netcentric--hlxsites.hlx.live

#28: Add Adobe Launch

---

blocks/header/header.js
blocks/hero/hero.js
blocks/leader-profiles/leader-profiles.js
blocks/related-blogs/related-blogs.js
scripts/lib-franklin.js
scripts/scripts.js
styles/styles.css

Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/drafts/mhaack/buttons
- After: https://global-buttons--netcentric--hlxsites.hlx.page/drafts/mhaack/buttons

feat: implement global button and link styles

---

scripts/delayed.js
scripts/scripts.js

Fix #88
Test URLs:
- After: https://no-launch--netcentric--hlxsites.hlx.page/

Improve embed loading

---

blocks/columns/columns-teasers.css
blocks/columns/columns.css
blocks/columns/columns.js
styles/styles.css

Fix #78
Todo: image should have same height
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/drafts/mhaack/layouts
- After: https://78-columns--netcentric--hlxsites.hlx.page/drafts/mhaack/layouts
- After: https://78-columns--netcentric--hlxsites.hlx.page/
- Before: https://main--netcentric--hlxsites.hlx.page/our-industries
- After: https://78-columns--netcentric--hlxsites.hlx.page/our-industries

feat: column variations

---

blocks/form/form.js

Test URL: https://issue-8--netcentric--hlxsites.hlx.page/lets-talk

chore: linting

---

helix-query.yaml
tools/importer/import.js

See #92 
Test URLs:
- After: https://author-index--netcentric--hlxsites.hlx.page/

chore: adapt importer for author profiles

---

styles/styles.css

Test URLs:
- After: https://styles-lint-fix--netcentric--hlxsites.hlx.page/

fix: styles lint issue

---

helix-query.yaml

fix blog image for index
Test URLs:
- After: https://image-index--netcentric--hlxsites.hlx.page/

fix: fix blog image for index

---

blocks/blog-posts/blog-posts.js
blocks/testimonial/testimonial.css
blocks/testimonial/testimonial.js
scripts/delayed.js

Fix #97 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/careers
- After: https://issue-97--netcentric--hlxsites.hlx.page/careers
- Before: https://main--netcentric--hlxsites.hlx.page/careers/netcentric-germany
- After: https://issue-97--netcentric--hlxsites.hlx.page/careers/netcentric-germany

Testimonials

---

blocks/blog-posts/blog-card.css
blocks/cards/cards.css
blocks/columns/columns.css
blocks/header/header.css
blocks/hero/hero.css
blocks/related-blogs/related-blogs.css
blocks/social/social.css
styles/styles.css

Fix #111 
Test URLs:
- After: https://issue-111--netcentric--hlxsites.hlx.page/

fix margins of existing blocks

---

scripts/delayed.js

Fix #23 
Test URLs:
- After: https://issue-23--netcentric--hlxsites.hlx.page/

Loading the LiveUX RUM collection script

---

blocks/blog-sidebar/blog-sidebar.css
blocks/blog-sidebar/blog-sidebar.js

Allows blocks to be part of blog articles, and adds a default author if the query fails.
Test URLs:
- Before: https://issue-14--netcentric--hlxsites.hlx.page/insights/2021/09/travel-marketing-automation
- After: https://issue-14-grid--netcentric--hlxsites.hlx.page/insights/2021/09/travel-marketing-automation
- Before: https://issue-14--netcentric--hlxsites.hlx.page/insights/2022/09/take-your-cx-strategy
- After: https://issue-14-grid--netcentric--hlxsites.hlx.page/insights/2022/09/take-your-cx-strategy

Issue 14 grid

---

blocks/cards/cards.css

Fix #41 
Test URLs:
- After: https://issue-41--netcentric--hlxsites.hlx.page/careers

fix: text font on side-by-side cards

---

blocks/hero/hero.css
scripts/delayed.js

Fix #118
Test URLs:
- After: https://issue-118--netcentric--hlxsites.hlx.page/

fix hero button on mobile

---

blocks/header/header.css

Fix #115 
Test URLs:
- After: https://issue-115--netcentric--hlxsites.hlx.page/

prevent scrolling if the header dropdown is open

---

blocks/blog-posts/blog-posts.js

Fix #122 
Test URLs:
- After: https://issue-122--netcentric--hlxsites.hlx.page/

add query parameter filter support to blog overview

---

scripts/scripts.js

Fix minor bug
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/insights/2018/10/a-howcase-to-smile-about
- After: https://fix-hero-autoblock--netcentric--hlxsites.hlx.page/insights/2018/10/a-howcase-to-smile-about

fix null exception in autoblock for hero

---

styles/styles.css

Minor fix to center sections for call to action areas
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/careers
- After: https://center-cta--netcentric--hlxsites.hlx.page/careers
(area in dark plum section should now be centered)

chore: center section for call to action areas

---

blocks/accordion/accordion.css

Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/what-we-do/experience-solutions
- After: https://fix-accordion-color--netcentric--hlxsites.hlx.page/what-we-do/experience-solutions

Fix accordion color

---

helix-query.yaml
helix-sitemap.yaml
robots.txt

Fix #110 
Test URLs:
- After: https://sitemap--netcentric--hlxsites.hlx.page/

feat: setup sitemap.xml & robots.txt

---

helix-sitemap.yaml

Test URLs:
- After: https://sitemap-fix--netcentric--hlxsites.hlx.page/

fix: fix sitemap base url

---

blocks/cards/cards.css
blocks/social/social.css
styles/styles.css

Adjust default heading color to dark plum. Section headings use respective colors as well.
Test URLs:
- After: https://heading-color--netcentric--hlxsites.hlx.page/

chore: use correct heading color be default

---

blocks/cta/cta.css
blocks/cta/cta.js

Fix #138 
Test URLs:
- After: https://issue-138--netcentric--hlxsites.hlx.page/

Issue 138 - Fix link at the end of the post to display as a button

---

helix-sitemap.yaml

Test URLs:
- After: https://<branch>--netcentric--hlxsites.hlx.page/

fix: fix sitemap lastmod

---

blocks/blog-posts/blog-card.css
blocks/related-blogs/related-blogs.css

Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/insights/2022/07/customer-data-platforms-pharma
- After: https://realted-blogs-header--netcentric--hlxsites.hlx.page/insights/2022/07/customer-data-platforms-pharma

fix: fix related blog header color

---

blocks/blog-posts/blog-card.css

Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/insights/2022/10/future-at-netcentric
- After: https://fix-blog-card-firefox--netcentric--hlxsites.hlx.page/insights/2022/10/future-at-netcentric

Fix blog card issue where firefox wouldn't display some avatars

---

blocks/logos/logos.css
blocks/logos/logos.js

Fix #80 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/drafts/jbeltran/image-list
- After: https://80-block-logos-block-design--netcentric--hlxsites.hlx.page/drafts/jbeltran/image-list

80 block logos block design

---

blocks/embed/embed.js

Fix #139
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/what-we-do/data-driven-experiences
- After: https://issue-139--netcentric--hlxsites.hlx.page/what-we-do/data-driven-experiences

Fixing the space issue for default emebed

---

blocks/columns/columns.css
styles/styles.css

Fix #114 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/our-industries
- After: https://issue-114-rewrite--netcentric--hlxsites.hlx.page/our-industries

Style "our industries" page

---

blocks/columns/columns.css

Fix #154
Test URLs:
- Test layouts:
- Before: https://main--netcentric--hlxsites.hlx.page/drafts/mhaack/layouts
- After: https://issue-154--netcentric--hlxsites.hlx.page/drafts/mhaack/layouts
- Marketing operations page
- Original: https://www.netcentric.biz/what-we-do/experience-operations/marketing-operations
- Before: https://main--netcentric--hlxsites.hlx.page/what-we-do/experience-operations/marketing-operations
- After: https://issue-154--netcentric--hlxsites.hlx.page/what-we-do/experience-operations/marketing-operations

Issue 154 - Support for columns with background

---

blocks/hero/hero.css

Fix #159 
Test URLs:
- After: https://159-css-class-secondary--netcentric--hlxsites.hlx.page/

#159 -Quick fix- Secondary class looks as it is

---

styles/styles.css

Fix #165 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/what-we-do/dav-reference-case
- After: https://165-linksheadlings-sections-are-wrong--netcentric--hlxsites.hlx.page/what-we-do/dav-reference-case

#165 link colors match its background

---

blocks/header/header.css
blocks/hero/hero.css
scripts/performance.js
scripts/scripts.js
styles/styles.css

https://micro-cls--netcentric--hlxsites.hlx.live/
vs.
https://main--netcentric--hlxsites.hlx.live/
reducing some micro `CLS` due to icon loading. (cc @ramboz) 
and...

chore: fix micro cls from icon loading

---

blocks/logos/logos.css
blocks/logos/logos.js
scripts/lib-franklin.js

Fix #158 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/ https://main--netcentric--hlxsites.hlx.page/what-we-do/data-driven-experiences https://main--netcentric--hlxsites.hlx.page/who-we-are
- After: https://158-complete-the-carousel-functionality--netcentric--hlxsites.hlx.page/ https://158-complete-the-carousel-functionality--netcentric--hlxsites.hlx.page/what-we-do/data-driven-experiences https://158-complete-the-carousel-functionality--netcentric--hlxsites.hlx.page/who-we-are

158 complete the carousel functionality

---

blocks/blog-footer/blog-footer.js
blocks/blog-posts/blog-posts.js
blocks/blog-sidebar/blog-sidebar.js
blocks/testimonial/testimonial.js

Fix #166
Test URLs:
- After: https://166-blogpost-profile-images--netcentric--hlxsites.hlx.page/
- Before: https://main--netcentric--hlxsites.hlx.page/insights/2022/09/take-your-cx-strategy
- After: https://166-blogpost-profile-images--netcentric--hlxsites.hlx.page/insights/2022/09/take-your-cx-strategy
- Before: https://main--netcentric--hlxsites.hlx.page/careers
- After: https://166-blogpost-profile-images--netcentric--hlxsites.hlx.page/careers

#166 author profile image has width & height

---

blocks/cards/cards.css

Fix #157 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/who-we-are
- After: https://157-adjust-text-cards--netcentric--hlxsites.hlx.page/who-we-are

#157 teaser cards have correct line height

---

blocks/blog-posts/blog-posts.js

fixes missing image alt on blog post teaser profile images
Test URLs:
- After: https://img-alt-fix--netcentric--hlxsites.hlx.page/

fix: image alt text

---

scripts/scripts.js

Test URLs:
- Before: https://rush-font--netcentric--hlxsites.hlx.page/
- After: https://rush-font-fix--netcentric--hlxsites.hlx.page/
- Before: https://rush-font--netcentric--hlxsites.hlx.page/insights/2022/09/content-at-scale
- After: https://rush-font-fix--netcentric--hlxsites.hlx.page/insights/2022/09/content-at-scale

await auto blocking to ensure blog sidebar block still gets decorated

---

scripts/lib-franklin.js

Test URLs:
- After: https://lint-errors--netcentric--hlxsites.hlx.page/

fix: lint-errors

---

blocks/blog-sidebar/blog-sidebar.css
blocks/fixed-social-media/fixed-social-media.css
blocks/fixed-social-media/fixed-social-media.js
scripts/scripts.js

Fix #194 
Test URLs:
- Before: https://main--cn-website--Netcentric.hlx.page/drafts/jbeltran/fixed-social-media
- After: https://194--cn-website--Netcentric.hlx.page/drafts/jbeltran/fixed-social-media

fixed social media block

---

blocks/logos/logos.js

Fix #215
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/ & https://main--cn-website--netcentric.hlx.page/what-we-do
- After: https://215-logos-slider--cn-website--netcentric.hlx.page/ & https://215-logos-slider--cn-website--netcentric.hlx.page/what-we-do

fix event listener

---

blocks/blog-footer/blog-footer.js
blocks/blog-posts/blog-posts.js
blocks/blog-sidebar/blog-sidebar.js
blocks/job-openings/job-openings.js
blocks/logos/logos.js
blocks/related-blogs/related-blogs.js
blocks/social/social.js
scripts/delayed.js
scripts/lib-franklin.js
scripts/scripts.js

Fix #81
Test URLs:
- After: https://81-placeholders--cn-website--netcentric.hlx.page/

use placeholders for translations

---

helix-query.yaml

Fix #230 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.live/
- After: https://230-add-search-index--cn-website--netcentric.hlx.live/

230 add search index

---

blocks/header/header.js
test/blocks/header/header.test.js

Fix #224 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.live/
- After: https://224-nav-override--cn-website--netcentric.hlx.live/

#224: try getting navigation path from metadata

---

styles/styles.css

Fix #235 
Test URLs:
- After: https://235-buttons-not-clickable--cn-website--netcentric.hlx.page/

remove margins from social media wrapper

---

blocks/footer/footer.js
blocks/header/header.js
scripts/lib-franklin.js
scripts/scripts.js
tools/importer/import.js

Fix #176 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.live/
- After: https://176-import-german--cn-website--netcentric.hlx.live/

176 import german

---

blocks/form/form-marketo.css
blocks/form/form.js

Fix #241
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/lets-talk
- After: https://241-cleanup-marketo-code--cn-website--netcentric.hlx.page/lets-talk
(Not tested in all forms)

241 cleanup marketo code

---

scripts/scripts.js

Test URLs:
- After: https://241-cleanup-marketo-code--cn-website--netcentric.hlx.page/

#241 add no-console and fix a typo

---

blocks/header/header.js

The language switcher now goes to the same page version when the user switches between languages
Fix #253
Test URLs:
- After: https://253-language-switcher-no-looks-properly--cn-website--netcentric.hlx.page/

#253 fix Language's links to switch page Language

---

blocks/blog-posts/blog-card.css
blocks/blog-posts/blog-posts.js
blocks/related-blogs/related-blogs.js

Only in insights and blog index pages
Fix #195 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/de/insights
- After: https://195-add-popup-for-blog-post-links--cn-website--netcentric.hlx.page/de/insights
- Before: https://main--cn-website--netcentric.hlx.page/de/insights/blog
- After: https://195-add-popup-for-blog-post-links--cn-website--netcentric.hlx.page/de/insights/blog

#195 popup shows in insights & blog index DE pages only

---

blocks/columns/columns.css

Fix #256
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/library/ncwebinars-expert-interview-digital-wave
- After: https://256-columns-18-85--cn-website--netcentric.hlx.page/library/ncwebinars-expert-interview-digital-wave

#256: add additional column layouts, 15-85 and no-gap

---

scripts/scripts.js
styles/two-columns.css
templates/two-columns/two-columns.js

Fix #255 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/library/ncwhitepapers-dde
- After: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/library/ncwhitepapers-dde
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/ncwhitepapers-dde
- After: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/drafts/jlledo/ncwhitepapers-dde
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/two-columns-demo
- After: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/drafts/jlledo/two-columns-demo

#255 build a form as inner block in a template

---

blocks/footer/footer.css
blocks/footer/footer.js
blocks/header/header.css
blocks/header/header.js
test/blocks/footer/footer.test.js

demo page: https://docs.google.com/document/d/1HY3JhsAMHiUFWPFi9N-vxy8F_FzstlrkAW1dEikCuMA/edit
BEFORE adding to prod, the new mini versions of header and footer need to be added to its final directory
temp mini header : /drafts/jlledo/nav-campaign
https://docs.google.com/document/d/1lkKCaf7Ux7rL0FRIv_Wg80WF8truCMQauYrvAkHmaCw/edit
temp mini footer : /drafts/jlledo/footer-campaign
https://docs.google.com/document/d/1HUJvCKWow_UoH5pcbtLl5BfImNnGtlE4FoqchxZNWe4/edit
Fix #184 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/campaign-demo
- After: https://184-implement-reduces-header-footer--cn-website--netcentric.hlx.page/drafts/jlledo/campaign-demo

#184 add header & footer mini 4 campaign template

---

blocks/search-results/search-results.css
blocks/search-results/search-results.js

Fix #245 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/search?terms=test
- After: https://245-improve-search-result-page-style--cn-website--netcentric.hlx.page/search?terms=test

245 improve search result page style

---

blocks/form/form.js

Also, if the URL has a lowercase F in the word mktForm in the Marketo url, is fixed here too 
but, if the URL is not valid, still does not render it at all
demo page:
https://docs.google.com/document/d/1VL54o5goOZfV63sIFyc3XHyvYBg5jQ8hVe71Xg76CPc/edit
Fix #273 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/marketo-forms-demo
- After: https://273-marketo-url-not-render-properly--cn-website--netcentric.hlx.page/drafts/jlledo/marketo-forms-demo

#273 Show the Marketo form if has a valid url

---

blocks/search-results/search-results.js

Test URLs:
- Before: https://www.netcentric.biz/search?terms=aaaa%22%3E%3Cmarquee%3E%3Cimg%20src=x%20onerror=confirm(document.domain)%3E
- After: https://encode-search-input--cn-website--netcentric.hlx.page/search?terms=aaaa%22%3E%3Cmarquee%3E%3Cimg%20src=x%20onerror=confirm(document.domain)%3E

encode search input

---

404.html

Only improve the styles of 404 page in English.
styles are based on the previous version
https://projects.netcentric.biz/wiki/display/NCWEB/Error+Page+Configuration+and+Handling
just change the 404.html for this thing as an example /does-not-exist
Fix #179 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/404.html
- After: https://179-correct-improved-404-handling--cn-website--netcentric.hlx.page/404.html

179 correct improved 404 handling

---

.github/workflows/liveux-release-annotation.yaml

#45: fix date format for liveux annotation api call

---

.github/workflows/liveux-release-annotation.yaml

#45: liveux annotation fix authentication

---

scripts/scripts.js

Test URLs:
- After: https://prioritize-header-loading--cn-website--netcentric.hlx.page/

do loadHeader call earlier not waiting for other blocks

---

blocks/blog-sidebar/blog-sidebar.js

Fix NCWEB-2591
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.live/insights/2023/03/adobe-aem-rockstar-2023
- After: https://ncweb-2591-xss--cn-website--netcentric.hlx.live/insights/2023/03/adobe-aem-rockstar-2023

NCWEB-2591: avoid XSS vector for social links

---

styles/styles.css

Test URLs:
- After: https://285-accessblity-banner-text--cn-website--netcentric.hlx.page/

285- Change text color for of banners for better acesseblity

---

head.html

Fix #337
Test URLs:
- After: view-source:https://337-origin-trail-bfcache--cn-website--netcentric.hlx.page/

#337: enable origin trails for bfcache on chrome

---

blocks/leader-profiles/leader-profiles-flyout.css
blocks/leader-profiles/leader-profiles.css
blocks/leader-profiles/leader-profiles.js

Fix #326 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/who-we-are
- After: https://326-flavour-to-leader-profile--cn-website--netcentric.hlx.page/drafts/sdhekale/leaderprofiledemo

326 flavour to leader profile

---

blocks/expanding-cards/expanding-cards.css
blocks/expanding-cards/expanding-cards.js

Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/careers/diversity-inclusion
- After: https://328-expanding-cards--cn-website--netcentric.hlx.page/drafts/mburicea/careers/expading-cards

328 expanding cards

---

styles/styles.css

Test URLs:
- After: https://366-default-text-color--cn-website--netcentric.hlx.page/what-we-do

366 - Changing text color to grey

---

blocks/spinning-cards/spinning-cards.css
blocks/spinning-cards/spinning-cards.js

Test URLs:
- After: https://334-block-7-spinning-cards--cn-website--netcentric.hlx.page/drafts/sdhekale/spinning-cards

334 - Spining cards implementation

---

blocks/leader-profiles/leader-profiles.css
blocks/leader-profiles/leader-profiles.js

Test URLs:
- After: https://380-low-quality-img-leader--cn-website--netcentric.hlx.page/drafts/sdhekale/leaderprofiledemo

380 - fix low quality image issue

---

blocks/multicolor-accordion/multicolor-accordion.css

I added new css selectors to target the buttons inside of the multicolor carousel.
Fix #381 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page//drafts/kweissenborn/dde-reveal
- After: https://381-multicolor-accordion-button-color--cn-website--netcentric.hlx.page/drafts/kweissenborn/dde-reveal

Fix #381 Multicolor accordion button colors

---

blocks/leader-profiles/leader-profiles-flyout.css

Fix #379-Remove automatically added comma on leader block
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/who-we-are
- After: https://379-removing-comma-from-leader-block--cn-website--Netcentric.hlx.page/who-we-are

Fix #379-Remove automatically added comma on leader block

---

blocks/job-openings/job-openings.css
blocks/job-openings/job-openings.js

Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/jobs
- After: https://391-cut-jobs-descriptions--cn-website--netcentric.hlx.page/jobs

Fix #391-Add size queries to iframe

---

blocks/job-openings/job-openings.css
blocks/job-openings/job-openings.js

Test URLs:
- After: https://391-cut-jobs-descriptions--cn-website--netcentric.hlx.page/

Fix #391-Set iframe fix height to 5500

---

styles/styles.css

Test URLs:
- After: https://376-default-link-color--cn-website--netcentric.hlx.page/

Fix #376-Change default link colour

---

blocks/cards/cards.css
blocks/cards/cards.js
blocks/header/header.js
blocks/leader-profiles/leader-profiles.css
styles/styles.css

Test URLs:
- After: https://ncbiz001-webperformance-improvements--cn-website--netcentric.hlx.page/

Ncbiz001 webperformance improvements

---

.gitignore
blocks/job-openings/job-openings.js

Test URLs:
- Before: https://main--cn-website--netcentric.aem.live/jobs?jobId=L758Y365
- After: https://feat-deep-link-job-details--cn-website--netcentric.aem.live/jobs?jobId=L758Y365

feat: add possibility to deep link to job details via url param

---

helix-query.yaml

Test URLs:
- Before: https://main--cn-website--netcentric.aem.live/
- After: https://<branch>--cn-website--netcentric.aem.live/

Testing sheetless index support

---

blocks/blog-posts/blog-card.css
blocks/header/header.css
blocks/hero/hero.css
styles/styles.css

Feature [#420](https://github.com/Netcentric/cn-website/issues/420)
Updated colors in Header, Banner, Content Sections and Hover States
Test URLs:
- Before: https://main--cn-website--netcentric.aem.live/
- After: https://421-update-header-banners-content--cn-website--netcentric.aem.live/

421 update header banners content
