tools/importer/import.js

Sets the image src before the preprocessing remove them.
Requires https://github.com/adobe/helix-importer/pull/41 and the corresponding cascading releases (helix-importer and helix-importer-ui)

feat: import preprocess for images

---

blocks/cards/cards.css

Adds another variation of the icons with text with different background
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/drafts/mhaack/icons-text
- After: https://icon-text-blue--netcentric--hlxsites.hlx.page/drafts/mhaack/icons-text

chore: add light-blue section version for icon-text card

---

helix-query.yaml

Fix index configs for blog
Test URLs:
- After: https://profile-index--netcentric--hlxsites.hlx.page/

chore: adapt index config

---

blocks/blog-posts/blog-card.css
blocks/blog-posts/blog-posts.css
blocks/blog-posts/blog-posts.js
blocks/related-blogs/related-blogs.css
blocks/related-blogs/related-blogs.js
scripts/delayed.js

Fix #18 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/insights/blog
- After: https://issue-18--netcentric--hlxsites.hlx.page/insights/blog

Add blog overview page

---

blocks/embed/embed.css
blocks/embed/embed.js

Adding the iFrame Embed block functionality for "Offerings" and "Diversity" sections.
Fix #54
Test URLs:
- After: https://issue-54--netcentric--hlxsites.hlx.page/

adding embed block for offerings and diversity embeds

---

blocks/leader-profiles/leader-profiles.css

Fix #161 
Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/who-we-are
- After: https://161-leader-profiles-name-with-wrong-color--netcentric--hlxsites.hlx.page/who-we-are

#161 leader profiles have correct header color

---

blocks/footer/footer.js
scripts/scripts.js

Fix link title handling for links text only.
Fix #192
Before:
After:
Test URLs:
- After: https://img-title-fix--netcentric--hlxsites.hlx.page/

fix: link title tweaks only for non img links

---

scripts/lib-franklin.js
scripts/performance.js
scripts/scripts.js
templates/blogpost/blogpost.js

most netcentric.biz pages do not have an image based `LCP` which is somewhat unusual and really doesn't work optimally with `LCP` guess in boilerplate code.
i tried to make the code a little bit flexible and replace the bandwidth waiting for `main img` with loading the main font... 
there is some negative impact to the `LCP` (obviously still well within the boundaries of `100`) but both `CLS` and subjective visual stability is greatly improved.
https://rush-font--netcentric--hlxsites.hlx.live/
vs.
https://main--netcentric--hlxsites.hlx.live/

improved LCP handling

---

blocks/header/header.css

cherry-picked from the previous PR
Fix #198
update: #207 
Test URLs:
- Before: https://main--cn-website--Netcentric.hlx.page/
- After: https://198-arrows-in-nav-are-missing--cn-website--Netcentric.hlx.page

#198 arrows not visible at top level nav in desktop

---

scripts/delayed.js
scripts/scripts.js

Fix #182
Since we anyway used the `IntersectionObserver` I moved the iframe creation back to `scripts.js.` While this improves the UX and the page feels loading faster it has negative impact on LHS (desktop only). As the video on the homepage is in the initial viewport and the `IntersectionObserver` is triggered immediately.
Test URLs:
- After: https://video-loading2--cn-website--netcentric.hlx.page/

chore: rework embed loading for videos & spotify

---

blocks/form/form.js
scripts/scripts.js

Fix #177 
Test URLs:
- https://177-marketo-auto-form--cn-website--netcentric.hlx.live/drafts/ahaller/ncwhitepaper-content-velocity

#177: added auto block for forms if only Marketo URL is present

---

blocks/header/header.css
blocks/header/header.js

The _/de/nav_ version has been updated using the previous AEM _de.html_ version and all links point to the _/de_ folder. Some links haven't **_/de_** version yet, so that goes to a 404 error (or redirects to the main version in PROD)
These links are broken by now:
- /de/how-we-work/aec-expert-community
Fix #248
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/de
- After: https://248-hide-search-on-german--cn-website--netcentric.hlx.page/de

#248 Search is hided in DE

---

helix-query.yaml

Fix #246 
Test URLs:
- https://246-german-index-file--cn-website--netcentric.hlx.page/

#246: add index definition for the German site tree

---

scripts/scripts.js

Tested using WhatFont google extension for chrome and font explorer in Firefox web browser
Fix #216 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/insights/2023/01/leveraging-adobe-integrations-to-deliver-personalized-customer-journeys-at-scale
- After: https://216-gellix-font-is-not-loaded-properly--cn-website--netcentric.hlx.page/insights/2023/01/leveraging-adobe-integrations-to-deliver-personalized-customer-journeys-at-scale

#216 Gellix font loads properly

---

styles/styles.css

This feature adds a new command keyword as section metadata style -> btn-center
Fix #286 
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/fan-engagement-platform
- After: https://286-center-button-only-from-text--cn-website--netcentric.hlx.page/drafts/jlledo/fan-engagement-platform

#286 add new class to center buttons only

---

.github/workflows/search-trigger.yaml

The search ingest REST API must be notified so it can pull content from query-index-search.yml . However, it takes around 60s for it to be updated. With this change, the pull for content should succeed.

Fix #295: Adds 90s delay to notify ingest API

---

scripts/delayed.js

add crossOrigin flag to LiveUX script to let the browser add the origin header on the request
Fix #362 
Test URLs:
- After: https://362-liveux-origin-header--cn-website--netcentric.hlx.page/

#362: LiveUX Origin header

---

blocks/related-blogs/related-blogs.js

Test URLs:
- After: https://373-blog-overview-goes-to-wrong--cn-website--netcentric.hlx.page/our-industries/financial-services-insurance

373 - change default link to blog overview button

---

blocks/chapter-cards/chapter-cards.css
blocks/chapter-cards/chapter-cards.js
icons/lock.svg
icons/plus.svg
scripts/lib-franklin.js

Test URLs:
- After: https://335-block-8-chapter-cards--cn-website--netcentric.hlx.page/drafts/sdhekale/chapter-cards

335 block 8 chapter cards

---

blocks/multicolor-accordion/multicolor-accordion.css
blocks/multicolor-accordion/multicolor-accordion.js
head.html

Test URLs:
- After: https://329-multicolour-accordion--cn-website--netcentric.hlx.page/drafts/sdhekale/multicolor-accordian

329 multicolour accordion

---

blocks/columns/columns.css

Fix ##392
Test URLs:
- After: https://392-benefits-icons-bug--cn-website--netcentric.hlx.page/
to fix this issue the class columns-3-cols needs to be added in the column container. I added a text-center class to center the text beneath each icon.

Fix #392-Add a class to center columns text

---

blocks/blog-footer/blog-footer.css
blocks/blog-footer/blog-footer.js
blocks/blog-posts/blog-posts.js
blocks/blog-sidebar/blog-sidebar.js
scripts/authors.js
scripts/lib-franklin.js

Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/drafts/gcibeira/blogpost-template-test
- After: https://383-blog-authors-not-showing--cn-website--netcentric.hlx.page/drafts/gcibeira/blogpost-template-test

383 blog authors not showing

---

scripts/lib-franklin.js
styles/styles.css

Fix #336
Test URLs:
- After: https://336-metadata-content-animation--cn-website--netcentric.hlx.page/drafts/vacosta/copy-of-index
To test this add a column with the key "animated" both on metadata and section metadata.
Values can be UP, LEFT, RIGHT, DOWN and NONE
To add animation on a general level:
To add animation on a section level:

336 metadata content animation

---

blocks/blog-posts/blog-card.css
blocks/blog-posts/blog-posts.css
blocks/blog-sidebar/blog-sidebar.css
blocks/cards/cards.css
blocks/chapter-cards/chapter-cards.css
blocks/columns/columns.css
blocks/expanding-cards/expanding-cards.css
blocks/fixed-social-media/fixed-social-media.css
blocks/flip-cards/flip-cards.css
blocks/footer/footer.css
blocks/form/gdpr.css
blocks/header/header.css
blocks/header/header.js
blocks/hero/hero.css
blocks/job-openings/job-openings.css
blocks/leader-profiles/leader-profiles-flyout.css
blocks/leader-profiles/leader-profiles.css
blocks/leader-profiles/leader-profiles.js
blocks/logos/logos.css
blocks/logos/logos.js
blocks/multicolor-accordion/multicolor-accordion.css
blocks/offices/offices.css
blocks/related-blogs/related-blogs.css
blocks/search-results/search-results.css
blocks/social/social.css
blocks/spinning-cards/spinning-cards.css
blocks/testimonial/testimonial.css
styles/styles.css
styles/two-columns.css

Streamlined all breakpoints to 600 / 900 / 1200 and all media queries to `min-width`
Test URLs:
- Before: https://main--cn-website--netcentric.hlx.live/drafts/documentation/block-inventory
- After: https://streamline-breakpoints--cn-website--netcentric.hlx.live/drafts/documentation/block-inventory

streamline viewport breakpoints according to best practises

---

.eslintignore
.gitignore
plugins/experimentation/.eslintignore
plugins/experimentation/.eslintrc.js
plugins/experimentation/.stylelintrc.json
plugins/experimentation/CODE_OF_CONDUCT.md
plugins/experimentation/LICENSE.md
plugins/experimentation/README.md
plugins/experimentation/package-lock.json
plugins/experimentation/package.json
plugins/experimentation/src/index.js
plugins/experimentation/src/preview.css
plugins/experimentation/src/preview.js
plugins/experimentation/src/ued.js
scripts/lib-franklin.js
scripts/scripts.js

Test URLs:
- Before: https://main--cn-website--netcentric.hlx.live/
- After: https://aem-experimentation--cn-website--netcentric.hlx.page/drafts/experiments/what-we-do

Instrument website with AEM Experimentation plugin

---

.github/pull_request_template.md
README.md
plugins/experimentation/README.md
plugins/experimentation/src/index.js
scripts/delayed.js
scripts/lib-franklin.js

Test URLs:
- Before: https://main--cn-website--netcentric.aem.live
- After: https://remove-liveux--cn-website--netcentric.aem.live

Remove obsolete LiveUX.
